test_that("judgeGtCombSr back stutter", {
  gtCombOne <- c(10, 10, 11, 12)
  peakOneL <- c(9, 10, 11, 12)
  heightOneL <- c(400, 2000, 1900, 2000)
  srFltr <- c(0.7, 0.35, 0.13, 0.12)
  srConsiderOneL <- rep(TRUE, 4)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
  heightOneL <- c(2100, 2000, 1900, 2000)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(TRUE, FALSE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
})

test_that("judgeGtCombSr forward stutter", {
  gtCombOne <- c(9, 10, 11, 11)
  peakOneL <- c(9, 10, 11, 12)
  heightOneL <- c(2100, 2000, 1900, 150)
  srFltr <- c(0.7, 0.35, 0.13, 0.12)
  srConsiderOneL <- rep(TRUE, 4)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
  heightOneL <- c(2100, 2000, 1900, 1000)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, TRUE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
})

test_that("judgeGtCombSr double-back stutter", {
  gtCombOne <- c(11, 12, 11, 11)
  peakOneL <- c(9, 10, 11, 12)
  heightOneL <- c(100, 200, 2100, 2000)
  srFltr <- c(0.7, 0.35, 0.13, 0.12)
  srConsiderOneL <- rep(TRUE, 4)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
  heightOneL <- c(1000, 200, 2100, 2000)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, TRUE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
})

test_that("judgeGtCombSr minus 2-nt stutter", {
  gtCombOne <- c(12, 13, 12, 13)
  peakOneL <- c(11, 11.2, 12, 13)
  heightOneL <- c(200, 100, 2100, 2000)
  srFltr <- c(0.7, 0.35, 0.13, 0.12)
  srConsiderOneL <- rep(TRUE, 4)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
  heightOneL <- c(200, 1000, 2100, 2000)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, FALSE, TRUE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), FALSE)
  srConsiderOneL <- c(FALSE, FALSE, FALSE, FALSE)
  expect_equal(judgeGtCombSr(gtCombOne, peakOneL, heightOneL, srFltr, srConsiderOneL), TRUE)
})
